### ISSUE TITLE
乐观并发控制问题是在加了这个字段之后发生的问题

### ISSUE THREAD

**Issue by maketochen** [fjykTec/ModernWMS#20]
`/// <summary>
    /// 模型基类
    /// </summary>
    [Serializable]
    public class BaseModel
    {
        /// <summary>
        /// ID
        /// </summary>
        [Key]
        [Column("id")]
        public int id { get; set; } = 0;

        /// <summary>
        /// 乐观并发控制
        /// </summary>
        [Timestamp]
        public byte[] RowVersion { get; set; } = null; ` 

RolemenuService/UpdateAsync 

![image](https://github.com/fjykTec/ModernWMS/assets/20569306/30d328a9-a710-4413-a03f-e708197469e8)

**Comment by tinsunchan** [comment]
报UpdateConcurrencyException异常，是你保存的RowVersion值与数据库对应数据的RowVersion值不一致。

**Comment by maketochen** [comment]
rowVersion 在其他界面并不需要手动赋值 
问题虽然已经解决了 但是我仍有疑问 为何需要手动在此赋值
![image](https://github.com/fjykTec/ModernWMS/assets/20569306/3b167a70-b635-4b88-a227-d9f106ca5404)

**Comment by ModernWMS** [comment]
在执行更新操作之前查询数据库中当前行的 RowVersion 值，并将其与要更新的实体的 RowVersion 值进行比较。如果这两个值不相等，则说明数据已经被其他用户或进程修改过（抛出异常），你就需要相应地处理这种情况，比如提示用户重新编辑数据或者自动合并数据。两边的RowVersion 要保持一致。

**Comment by maketochen** [comment]
谢谢，明白了，因为之前查询了一遍所以导致这个问题，加上RowVersion版本对比后就可以解决这个乐观并发控制了。
