### ISSUE TITLE
Installation went smoothly, but there was a timeout prompt when logging in to the frontend

### ISSUE THREAD

**Issue by billydu1980** [fjykTec/ModernWMS#39]
Ubuntu 22.04 system, ModernWMS installation and configuration process without any errors. When logging in to the front-end webpage, it prompts operation timeout. Backend: 20011 accesses normally;
When compiling the front-end code, I noticed the documentation prompt and edited the. env. production file to define the actual IP address of the server.
In addition, the default database file/ModernWMS/backend/wms.db has not been changed.

Also, please let me know if there are any other configuration requirements besides modifying the appsettings. json file if we use PostgreSQL database instead? Please provide a clear answer.

 
![back](https://github.com/user-attachments/assets/8a7dec6b-e2a2-4049-b02a-9e5e81124e6e)
![timeout](https://github.com/user-attachments/assets/4110ca28-7c04-4984-85b7-c43801cee38f)

Best regards!
adu

**Comment by billydu1980** [comment]
Why hasn't anyone responded? Can this software still be used by somebody?
Why do open source software intentionally set bugs, and how can more people participate in testing.

**Comment by 809388027** [comment]
Hello, this issue is usually due to a problem with the backend address configured in the front-end project. Based on your configuration, the .env.production should be set to:
![image](https://github.com/user-attachments/assets/5f5e81fa-fd9f-44a4-a6a1-d16a17fce30e)
After saving the changes, simply run npm run build to deploy.

**Comment by 809388027** [comment]
If you are in the development environment, the file you should modify is: .env.development.

**Comment by billydu1980** [comment]
Dear all:
I have noticed the details of modifying. env. introduction or. env. development., but the error still persists. I have read many messages from people who have also encountered this issue, but no one has replied that it has been resolved. I hope this issue can be recorded as resolved.

Thank you very much. Here is my configuration process document.


[install&config-ModernWMS.txt](https://github.com/user-attachments/files/17057815/install.config-ModernWMS.txt)

Thanks so much!
adu

**Comment by billydu1980** [comment]
I have found the reason and need to configure the Postgres database firstly

## postgresql 
sudo -i -u postgres
psql
ALTER USER postgres WITH PASSWORD '123456';
CREATE DATABASE wms;
\list
\q
exit

##Import database script
sudo -u postgres psql -d wms -f database_postgresql.sql

##Change database type
 nano /ModernWMS/backend/appsettings.json

  "AllowedHosts": "*",
  "Database": { "db": "PostGres" },
  "ConnectionStrings": {
     "PostGresConn": "Server=192.168.1.141;Port=5432;User Id=postgres;Password=123456;Database=wms;"
